### ISSUE TITLE
Add more docs

### ISSUE THREAD

**Issue by klahnakoski** [evhub/cpyparsing#2]
This is an interesting project, but I am lost about how it relates to `pyparsing`: If I modify `pyparsing`, do those changes end up over here?

**Comment by evhub** [comment]
@klahnakoski No--`cpyparsing` is currently on `pyparsing` version `2.2.0`, which is somewhat out-of-date at this point. It needs to be manually updated to new `pyparsing` versions, which it probably should be.

**Comment by klahnakoski** [comment]
Thank you.  There is a small chance that a GSOC student may work on the pyparsing project. I was wondering if that work can be used here, eventually.

**Comment by evhub** [comment]
@klahnakoski I just went through and updated cpyparsing to the latest pyparsing `2.3.2` version.
