### ISSUE TITLE
release tags on GitHub

### ISSUE THREAD

**Issue by MeggyCal** [evhub/cpyparsing#3]
Hi, could you please tag any future releases also on GitHub? Thanks!

**Comment by evhub** [comment]
@MeggyCal What's the use case for this? Is the [PyPI version history](https://pypi.org/project/cPyparsing/#history) not sufficient?

**Comment by MeggyCal** [comment]
Hi, sorry for late answer. I would like to launch runtime tests myself for each release, so I need some tarball with tests. You could add them to PyPi tarball (some people consider it uggly) or you could tag them in the repo. Or you could think out your own creative way :) . Thanks a lot!

**Comment by evhub** [comment]
@MeggyCal Tests should now be included in future PyPI releases. I will also try to remember to tag future releases on GitHub, though I'd suggest using the PyPI tarball instead as that is guaranteed to always be correct.
